spring:
  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
    publisher-returns: true
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual